
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "flask", "run", "--host=0.0.0.0"]

  frontend:
    build:
      context: ./frontend
      args:
        #VITE_API_URL: http://backend:5000
        VITE_API_URL: ${API_HOST}
    environment:
      #- VITE_API_URL=http://backend:5000
      - VITE_API_URL=${API_HOST}
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
