apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=         # base64 for 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=     # base64 for 'postgres'
